### ISSUE TITLE
markAsReadNotification doesn't work 

### ISSUE THREAD

**Issue by junichi11** [nulab/backlog4j#19]
I tried running the following:

```java
backlogClient.markAsReadNotification(notification.getId());
```
But it seems that the notification is not marked as read.

#### Backlog4j
2.1.3

Thanks.

**Comment by kimzo** [comment]
Humm...
Can you try using 2.1.4-SNAPSHOT ?
In my local, after creating notifications ,
below test is pass using 2.1.4-SNAPSHOT .
```
        ResponseList<Notification> notifications = userBacklog.getNotifications();
        GetNotificationCountParams params = new GetNotificationCountParams();
        params.resourceAlreadyRead(false);
        int preCount = userBacklog.getNotificationCount(params);

        // when
        for(Notification notification : notifications){
            if(!notification.isAlreadyRead()){
                userBacklog.markAsReadNotification(notification.getId());

            }
        }
        int aftCount = userBacklog.getNotificationCount(params);

        assertThat(preCount , greaterThan(aftCount));
```

And In few days we are going to release 2.1.4.

**Comment by kimzo** [comment]
release of 2.1.4(contains pull request api support) is maybe in next week.

**Comment by junichi11** [comment]
> Can you try using 2.1.4-SNAPSHOT ?

I tried using it. But markAsReadNotification method doesn't work... resetNotificationCount()(marked as read) and getNotificationCount() are work fine.

Is this an API's problem? If so, should I submit this issue to [1] ?

[1] http://feedback.backlog.jp/

**Comment by kimzo** [comment]
There are two type of "alreadyRead" params in notification data model.

one is "alreadyRead". and is changed by resetNotificationCount(). 
two is "resourceAlreadyRead". and is changed by markAsReadNotification()

it is assumed that "alreadyRead" is used for counting notifications like backlog's header notification count. and "resourceAlreadyRead" is used for checking Whether the notification's issue or wiki was opened or not. it is complex...

below is how to confirm backlog notification api spec.
 
1.get before mark as read
https://xxx_space.backlog.jp/api/v2/notifications?apiKey=XXX_api_key
```
        "id": 10xxxx9,
        "alreadyRead": false,
        "reason": 2,
        "resourceAlreadyRead": false,
        "project": {
            "id": 2xxx4,
            "projectKey": "TESTTEST",
            "name": "TEST",
            "chartEnabled": true,
            "subtaskingEnabled": false,
            "textFormattingRule": "markdown",
            "archived": false,
            "displayOrder": 5
        },
```

2.post for reset
https://xxx_space.backlog.jp/api/v2/notifications/markAsRead?apiKey=XXX_api_key

3.get after reset
https://xxx_space.backlog.jp/api/v2/notifications?apiKey=XXX_api_key
```
        "id": 10xxxx9,
        "alreadyRead": true,
        "reason": 2,
        "resourceAlreadyRead": false,
        "project": {
            "id": 2xxx4,
            "projectKey": "TESTTEST",
            "name": "TEST",
            "chartEnabled": true,
            "subtaskingEnabled": false,
            "textFormattingRule": "markdown",
            "archived": false,
            "displayOrder": 5
        },
```

4.post for mark as read
https://xxx_space.backlog.jp/api/v2/notifications/10xxxx9/markAsRead?apiKey=XXX_api_key

5.get after mark as read
https://xxx_space.backlog.jp/api/v2/notifications?apiKey=XXX_api_key
```
        "id": 10xxxx9,
        "alreadyRead": true,
        "reason": 2,
        "resourceAlreadyRead": true,
        "project": {
            "id": 2xxx4,
            "projectKey": "TESTTEST",
            "name": "TEST",
            "chartEnabled": true,
            "subtaskingEnabled": false,
            "textFormattingRule": "markdown",
            "archived": false,
            "displayOrder": 5
        },
```

**Comment by junichi11** [comment]
@kimzo Oh, I see now. My usage was wrong. Sorry, I confused a bit. `isResourceAlreadyRead` works for me. 
Thanks a lot for explaining!

**Comment by kimzo** [comment]
I am grad to help :)
