### ISSUE TITLE
Can't get an issue count with a keyword

### ISSUE THREAD

**Issue by junichi11** [nulab/backlog4j#21]
I can't get an issue count with a keyword. But I can get it if the keyword is empty. (Is my usage wrong?)

#### Reproducible code
```java
GetIssuesCountParams countParams = new GetIssuesCountParams(Collections.singletonList(project.getId()))
                .keyword("test");

int issuesCount = backlogClient.getIssuesCount(countParams);
```

#### Actual results
An Exception is thrown.

com.nulabinc.backlog4j.BacklogAPIException: backlog api request failed.
status code - 400
message - /data/lucene/index/5357/segments_5x (そのようなファイルやディレクトリはありません)
code - 1

#### Expected results

We can get the issue count with the keyword.

#### Backlog4j
2.1.4

Thanks.

**Comment by kimzo** [comment]
Thank you for your report.
Probably, it's the API servers temporary error with keyword searching. So please wait for a while till the server response is fixed.

>message - /data/lucene/index/5357/segments_5x (そのようなファイルやディレクトリはありません)

But this message is not so good, we should change it.

**Comment by junichi11** [comment]
> Probably, it's the API servers temporary error with keyword searching. So please wait for a while till the server response is fixed.

I see. I'll wait :)

> But this message is not so good, we should change it.

:+1: 

Thank you!

**Comment by junichi11** [comment]
It has been fixed :)

http://feedback.backlog.jp/forums/140671-backlog-%E8%A6%81%E6%9C%9B-%E5%95%8F%E9%A1%8C%E3%81%AE%E5%A0%B1%E5%91%8A-%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A9%E3%83%A0/suggestions/9637746-api-v2-%E3%81%A7%E3%82%AD%E3%83%BC%E3%83%AF%E3%83%BC%E3%83%89%E3%82%92%E6%8C%87%E5%AE%9A%E3%81%97%E3%81%9F%E8%AA%B2%E9%A1%8C%E3%81%AE%E5%8F%96%E5%BE%97%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84

Thanks.

**Comment by kimzo** [comment]
Thank you for asking and confirming!
