### ISSUE TITLE
SharedFile#getUpdated が実装されていない

### ISSUE THREAD

**Issue by k4200** [nulab/backlog4j#29]
https://developer.nulab-inc.com/docs/backlog/api/2/get-sharedfiles
の `updated` が取得できないので、実装してもらえませんか。

**Comment by kimzo** [comment]
返答随分遅れてしまい申し訳ないです 😢 
I'll fix it. so please wait a little longer.

**Comment by kimzo** [comment]
修正ずみなのでcloseしますね
