### ISSUE TITLE
"Get List of Shared Files" の order, offset, count を渡す手段が無い

### ISSUE THREAD

**Issue by k4200** [nulab/backlog4j#30]
https://developer.nulab-inc.com/docs/backlog/api/2/get-sharedfiles
の Query Parameters を渡す手段が無いように見えます。

`GetIssuesParams` と同様に、 `GetFilesParams` クラスを作成して、それを渡せるようになっていると使いやすいので、ご検討をお願いします。

**Comment by kimzo** [comment]
こちらも検討と対応進めます。
Sorry, Please wait a little more.

**Comment by kimzo** [comment]
こちらも修正ずみのためcloseしますね
