### ISSUE TITLE
BacklogClient.postAttachment で アップロードしたファイルの最後に \r\n が付与される

### ISSUE THREAD

**Issue by OdaShinsuke** [nulab/backlog4j#33]
ファイルの最後に「\r\n」 が付くため、アップロードしたファイルをダウンロードしたら正常に開けない。(.xlsx 等)  

https://github.com/nulab/backlog4j/blob/v2.2.0/src/main/java/com/nulabinc/backlog4j/http/BacklogHttpClientImpl.java#L226

この行を削除したら解消しました。

**Comment by yuichi0301** [comment]
@OdaShinsuke 

ご連絡いただきありがとうございます。
確かに現象が再現できましたので修正いたしました。
まだmavenまでリリースはされていません。

**Comment by kimzo** [comment]
release 済みなのでcloseします
