### ISSUE TITLE
Issue の custom field の値を取るにはどうすればいいでしょうか

### ISSUE THREAD

**Issue by KenjiOhtsuka** [nulab/backlog4j#35]
Issue のカスタムフィールドの値を取るにはどのようにすればいいでしょうか。

getIssues で issueを取得した後の手順を教えてください

**Comment by yuichi0301** [comment]
@KenjiOhtsuka 

こちら次のようにissueごとにgetCustomFieldsメソッドを使用して課題に付属しているカスタムフィールドの値を取得します。複数の値が付属していることがあるためリストになっています。
```
issue.getCustomFields()
```
その後１つずつキャストし値を取得します。
```
TextCustomField textCustomField = (TextCustomField)customField;
System.out.println(textCustomField.getValue());
```
サンプルを書きましたのでご参照ください。

https://gist.github.com/yuichi0301/df2ad82aa18a5746385127700d6d0645

**Comment by KenjiOhtsuka** [comment]
キャストが必要なんですね。
ありがとうございます。やってみます。
