### ISSUE TITLE
com.nulabinc.backlog4j.internalのパッケージにアクセスしないとリスト形式のカスタムフィールドのIDを取得できない

### ISSUE THREAD

**Issue by megascus** [nulab/backlog4j#39]
画面からリスト形式のカスタムフィールドを設定するときには値の名前は指定できますが、値のIDは指定できません。

イシューを作成するAPIを叩くときにカスタムフィールドの値を追加できますが、値の設定が値の名前ではなく、値のIDが必要なため、一度BacklogClient#getIssueTypes(String)を叩いてCustomFieldSettingを取得しますが、そちらの公開APIでは値の名前から値のIDを取得するAPIが存在しません。
そのため、現状では、内部APIのMultipleListCustomFieldSetting/SingleListCustomFieldSettingに一度キャストをしてあげる必要があるようです。

こちらについて使用上非常に面倒くさいというのもあるのでapiを叩くときにカスタムフィールドについては値のIDだけではなく、値の名前でも登録できるように変更できないでしょうか？

**Comment by megascus** [comment]
タイトルの問題の解決であれば、CustomFieldSettingに List<ListItemSetting> getItems()を追加してくれるだけでもいいですと思ったけど、ListItemSettingクラス自体もinternalパッケージなのか。

**Comment by kimzo** [comment]
>こちらについて使用上非常に面倒くさいというのもあるのでapiを叩くときにカスタムフィールドについては値のIDだけではなく、値の名前でも登録できるように変更できないでしょうか？

ご不便おかけして申し訳ないです。面倒ですよね、あとキャストとかしたくないですよね...

リスト形式のカスタムフィールドでは、値の名前の重複が許されているのでIDに変換するところで一意にならず、IDの若いものに振り当てるとかすると思わぬ不具合を引き起こしそうな感じがしますね。便利そうなんですけど。
少し検討します！

**Comment by megascus** [comment]
よろしくお願いします。
ちなみに、List getItems()を追加というのは以下のようなイメージです。
https://github.com/megascus/backlog4j/commit/4c8a51327d9e4867ed07a0417b161568d1383d3c?diff=split

**Comment by kimzo** [comment]
>ちなみに、List getItems()を追加というのは以下のようなイメージです。
そのような感じのものを追加してみましたのでお試しください。
SNAPSHOT versionのみdeployされています。

**Comment by megascus** [comment]
@kimzo 
ありがとうございます。internalパッケージ内のクラスへのキャストが不要になったため、コードがすっきりしました。

**Comment by kimzo** [comment]
値の名前はいろいろ考慮しないといけなくて (API側が対応してないのもあり)、ちょっと対応は置いておこうかと思います。
なのでこのままクローズさせてもらいますね☺️
