### ISSUE TITLE
PullRequestQueryParams の issueIds にはいくつまでIDを追加できますか？

### ISSUE THREAD

**Issue by KenjiOhtsuka** [nulab/backlog4j#40]
https://developer.nulab-inc.com/ja/docs/backlog/api/2/get-pull-request-list/

pullrequest の一覧を取得するときに、 issueIds を条件にして取得したいと考えているのですが、
この issueIds にはいくつまで値を追加できるでしょうか。

pullrequest一覧のレスポンスに表示される pullrequest の数に上限はあるでしょうか。

**Comment by kimzo** [comment]
>この issueIds にはいくつまで値を追加できるでしょうか。

確かめてないですが特に上限はないと思います。

>pullrequest一覧のレスポンスに表示される pullrequest の数に上限はあるでしょうか

以下のようにパラメータについて書かれているので上限は100かと
> count	数値	取得上限(1-100) 指定が無い場合は20
