### ISSUE TITLE
No change log for 2.5.3

### ISSUE THREAD

**Issue by baseballyama** [nulab/backlog4j#91]
[README.md](https://github.com/nulab/backlog4j#updates) says 

> 2023/07/27 2.5.3 released

So I checked https://github.com/nulab/backlog4j/releases, but I couldn't find changelog for 2.5.3.
Can you add a changelog for the version?

**Comment by baseballyama** [comment]
Perhaps they did not add it because it does not affect the production code, but it is inconvenient not to have a description of the changes when users update a library.

**Comment by yuichi0301** [comment]
@baseballyama 

I'm late adding the changelog. I added a changelog. thank you.

https://github.com/nulab/backlog4j/releases/tag/v2.5.3

**Comment by baseballyama** [comment]
Thank you!
